#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Homework1/Homework1.csproj", "Homework1/"]
RUN dotnet restore "Homework1/Homework1.csproj"
COPY . .
WORKDIR "/src/Homework1"
RUN dotnet build "Homework1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Homework1.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Homework1.dll"]